# Название или путь к модели GPT-3, которую нужно загрузить
model_name: "sberbank-ai/rugpt3small_based_on_gpt2"

# Параметры генерации текста
max_length: 70  # Максимальная длина генерируемого текста
repetition_penalty: 5.0  # Штраф за повторение слов, помогает избежать одинаковых фраз
top_k: 5  # Использовать только top_k самых вероятных слов на каждом этапе генерации
top_p: 0.95  # Ограничение вероятности: выбирает слова до тех пор, пока их совокупная вероятность не достигнет значения
temperature: 1.0  # Температура, которая управляет случайностью выборки слов
num_beams: 20  # Количество "лучей" в лучевом поиске, улучшает качество текста
no_repeat_ngram_size: 3  # Минимальный размер n-грамм, которые не должны повторяться в тексте
